# usage
## git tag -a v0.1 -m "test relaese"
stages:
  - release
release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [""]
  only:
    - tags
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release --clean
